apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodemetric-collector
  namespace: default
spec:
  selector:
    matchLabels:
      app: nodemetric-collector
  template:
    metadata:
      labels:
        app: nodemetric-collector
    spec:
      hostNetwork: true
      # serviceAccountName: metrics-collector
      containers:
      - name: nodemetric-collector
        image: ptrvx/network-collector:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 5201  # iperf3 port
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "250m"
            memory: "500Mi"
