apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemetric-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodemetric-controller
  template:
    metadata:
      labels:
        app: nodemetric-controller
    spec:
      containers:
        - name: nodemetric-controller
          image: ptrvx/network-collector
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              memory: 512Mi
              cpu: "250m"
            requests:
              memory: 128Mi
              cpu: "100m"